### PR TITLE
Adds assorted movies

### PR DESCRIPTION
**Pull request by EdgarBarrantes**
Adds recent Sherlock Holmes movies, V for Vendetta and Monty Python films.

### CODE REVIEW

**Comment by lsmoura** [comment]
Hi! Thanks for all the help. You forgot the “.json” on the file names. (On both PRs)

**Comment by EdgarBarrantes** [comment]
Hi! Right! Sorry, there you are. I just saw the mess, let me know if we close these and open new cleaner PRs.

**Comment by lsmoura** [comment]
No need for a new PR. You’re still missing some “.json” on some files. If I get to a computer before you can fix this, I’ll fix it for you. No need to lose all this work!

**Comment by EdgarBarrantes** [comment]
Cheers. Do you know what jshint is complaining about?

**Comment by lsmoura** [comment]
The two Sherlock Holmes movies had a dangling comma. I've fixed and merged. I'm also updating the tests to be more verbose about this kind of error.

**Pull request merged**
