### PR TITLE
Add Baahubali-2 and its actors

### PR DESCRIPTION
**Pull request by vvyomjjain**
I have added the movie Baahubali 2: The conclusion to movies/2017 and also the actors individually in the actors folder as well. I look forward to contribute more towards this repo.

### CODE REVIEW

**Comment by vvyomjjain** [comment]
I'll be adding more bollywood movies in the very near future.

**Comment by vvyomjjain** [comment]
I have added the file raees.json, I am new to this whole PR thing. Can anyone help me understand what does it mean by "All checks have failed". Is it an invalid commit or something. I even checked the details but couldn't comprehend anything. The branch seems to have no conflicts with the base branch. Help me out guys. Thanks.

**Comment by DoctaRay** [comment]
It says the naming is wrong. It's probably something with the way you committed the code. Check this link out for more info: https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

**Comment by vvyomjjain** [comment]
Thank you @DoctaRay and @blue-atom for guiding me. Finally all tests are passed.

**Comment by lsmoura** [comment]
Yay! You found typos! Perfect!!

**Pull request merged**
